name: Verify PR title/description

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: aspect-forks/action-semantic-pull-request@72d599af21617762a000f7047db60d0e328ef598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
